color = input("Enter your favourite color ")
place = input("Enter your favourite place ")
cloth = input("Enter your favourite cloth ")
sport = input("What's your favourite sport? ")
season = input("What's your favourite season? ")
print("I always " +sport + " in the " + place)
print("I love wearing " + color + " " + cloth + " in " + season)
print("On an " + season + " morning, I was wearing " + color + " " + cloth + " and " + sport + " in the  " + place)
